os: linux
dist: bionic
language: shell
git:
  quiet: true
env:
  global:
    - HADOLINT_VERSION=1.18.2
services:
- docker
before_install:
- sudo curl -L https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
- sudo chmod 755 /usr/local/bin/hadolint
install:
- docker build
  --no-cache
  --tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} .
script:
- DOCKERCONTAINER=$(docker run -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT})
- sleep 5
- docker ps -f id=${DOCKERCONTAINER}
- hadolint --ignore DL3007 Dockerfile
- docker stop ${DOCKERCONTAINER} && docker rm -fv ${DOCKERCONTAINER}
after_success:
- docker tag ${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT} quay.io/aminvakil/archlinux:devel
- docker login quay.io -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD"
- docker push quay.io/aminvakil/archlinux:devel
