FROM archlinux:base-20211121.0.39613

ENV container docker

LABEL maintainer="Amin Vakil <info@aminvakil.com>"

ENV LANG=en_US.UTF-8

RUN pacman -Syu --noconfirm base-devel && \
    rm -rf /var/cache/pacman/pkg/* && \
    useradd -m devel && echo "devel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/01_devel

ENTRYPOINT ["/usr/lib/systemd/systemd"]
