FROM archlinux:base-20230514.0.150299

ENV container docker

LABEL maintainer="Amin Vakil <info@aminvakil.com>"

RUN pacman -Syu --noconfirm base-devel && \
    rm -rf /var/cache/pacman/pkg/* && \
    useradd -m devel && echo "devel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/01_devel

ENTRYPOINT ["/usr/lib/systemd/systemd"]
